import { useState } from 'react';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Dialog, DialogContent, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { Download, FileText, User, Calendar, Phone, IdCard, CheckCircle, X } from 'lucide-react';
import jsPDF from 'jspdf';

interface PatientInfo {
  mruNumber: string;
  visitId: string;
  fullName: string;
  age: number;
  gender: string;
  contactPhone: string;
  bloodGroup?: string;
  registrationDate: string;
}

interface ConsultationCardModalProps {
  isOpen: boolean;
  onClose: () => void;
  patientInfo: PatientInfo;
}

export function ConsultationCardModal({ isOpen, onClose, patientInfo }: ConsultationCardModalProps) {
  const [isDownloading, setIsDownloading] = useState(false);

  const generateConsultationCard = async () => {
    setIsDownloading(true);
    
    try {
      const pdf = new jsPDF();
      const pageWidth = pdf.internal.pageSize.getWidth();
      const margin = 20;
      
      // Header
      pdf.setFillColor(33, 150, 243); // Blue background
      pdf.rect(0, 0, pageWidth, 40, 'F');
      
      pdf.setTextColor(255, 255, 255);
      pdf.setFontSize(24);
      pdf.setFont('helvetica', 'bold');
      pdf.text('NAKSHATRA HOSPITAL', pageWidth / 2, 20, { align: 'center' });
      
      pdf.setFontSize(14);
      pdf.setFont('helvetica', 'normal');
      pdf.text('Patient Consultation Card', pageWidth / 2, 30, { align: 'center' });
      
      // Reset text color for content
      pdf.setTextColor(0, 0, 0);
      
      // Patient Information Section
      let yPos = 60;
      
      pdf.setFontSize(18);
      pdf.setFont('helvetica', 'bold');
      pdf.text('Patient Information', margin, yPos);
      
      yPos += 20;
      pdf.setFontSize(12);
      pdf.setFont('helvetica', 'normal');
      
      // Patient details
      const details = [
        { label: 'MRU Number:', value: patientInfo.mruNumber },
        { label: 'Visit ID:', value: patientInfo.visitId },
        { label: 'Patient Name:', value: patientInfo.fullName },
        { label: 'Age:', value: `${patientInfo.age} years` },
        { label: 'Gender:', value: patientInfo.gender },
        { label: 'Phone:', value: patientInfo.contactPhone },
        { label: 'Blood Group:', value: patientInfo.bloodGroup || 'Not specified' },
        { label: 'Registration Date:', value: new Date(patientInfo.registrationDate).toLocaleDateString() },
      ];
      
      details.forEach((detail) => {
        pdf.setFont('helvetica', 'bold');
        pdf.text(detail.label, margin, yPos);
        pdf.setFont('helvetica', 'normal');
        pdf.text(detail.value, margin + 50, yPos);
        yPos += 15;
      });
      
      // Consultation Details Section
      yPos += 10;
      pdf.setFontSize(16);
      pdf.setFont('helvetica', 'bold');
      pdf.text('Consultation Details', margin, yPos);
      
      yPos += 20;
      pdf.setFontSize(12);
      pdf.setFont('helvetica', 'normal');
      
      // Consultation form fields
      const consultationFields = [
        'Chief Complaint: ________________________________',
        '',
        'History of Present Illness:',
        '_________________________________________________',
        '_________________________________________________',
        '_________________________________________________',
        '',
        'Physical Examination:',
        '_________________________________________________',
        '_________________________________________________',
        '',
        'Diagnosis: ______________________________________',
        '',
        'Treatment Plan:',
        '_________________________________________________',
        '_________________________________________________',
        '',
        'Prescriptions:',
        '_________________________________________________',
        '_________________________________________________',
        '',
        'Follow-up Date: __________________',
        '',
        'Doctor Signature: _______________________________',
        '',
        'Date: _______________'
      ];
      
      consultationFields.forEach((field) => {
        if (yPos > 250) { // New page if needed
          pdf.addPage();
          yPos = 30;
        }
        pdf.text(field, margin, yPos);
        yPos += 10;
      });
      
      // Footer
      pdf.setFontSize(10);
      pdf.setFont('helvetica', 'italic');
      pdf.text('Generated by Nakshatra Hospital Management System', pageWidth / 2, pdf.internal.pageSize.getHeight() - 10, { align: 'center' });
      
      // Save the PDF
      pdf.save(`Consultation_Card_${patientInfo.mruNumber}.pdf`);
      
    } catch (error) {
      console.error('Error generating consultation card:', error);
    } finally {
      setIsDownloading(false);
    }
  };

  return (
    <Dialog open={isOpen} onOpenChange={onClose}>
      <DialogContent className="max-w-md mx-auto">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2 text-green-600">
            <CheckCircle className="h-6 w-6" />
            Registration Successful!
          </DialogTitle>
        </DialogHeader>
        
        <div className="space-y-6">
          {/* Success Message */}
          <div className="text-center">
            <div className="mx-auto w-16 h-16 bg-green-100 rounded-full flex items-center justify-center mb-4">
              <User className="h-8 w-8 text-green-600" />
            </div>
            <h3 className="text-lg font-semibold text-gray-900 mb-2">
              Patient Successfully Registered
            </h3>
            <p className="text-gray-600 text-sm">
              {patientInfo.fullName} has been registered with MRU: {patientInfo.mruNumber}
            </p>
          </div>

          {/* Patient Summary Card */}
          <Card className="border-green-200">
            <CardHeader className="pb-3">
              <CardTitle className="text-sm font-medium text-gray-700">Patient Summary</CardTitle>
            </CardHeader>
            <CardContent className="space-y-2">
              <div className="flex justify-between text-sm">
                <span className="flex items-center gap-2">
                  <IdCard className="h-4 w-4 text-blue-500" />
                  MRU Number:
                </span>
                <span className="font-semibold">{patientInfo.mruNumber}</span>
              </div>
              <div className="flex justify-between text-sm">
                <span className="flex items-center gap-2">
                  <User className="h-4 w-4 text-green-500" />
                  Patient Name:
                </span>
                <span className="font-semibold">{patientInfo.fullName}</span>
              </div>
              <div className="flex justify-between text-sm">
                <span className="flex items-center gap-2">
                  <Calendar className="h-4 w-4 text-purple-500" />
                  Age/Gender:
                </span>
                <span className="font-semibold">{patientInfo.age} years, {patientInfo.gender}</span>
              </div>
              <div className="flex justify-between text-sm">
                <span className="flex items-center gap-2">
                  <Phone className="h-4 w-4 text-orange-500" />
                  Phone:
                </span>
                <span className="font-semibold">{patientInfo.contactPhone}</span>
              </div>
            </CardContent>
          </Card>

          {/* Download Options */}
          <div className="space-y-3">
            <div className="text-center">
              <FileText className="h-12 w-12 text-blue-500 mx-auto mb-2" />
              <h4 className="font-semibold text-gray-900">Download Consultation Card</h4>
              <p className="text-sm text-gray-600 mt-1">
                Get a pre-formatted consultation card for the doctor visit
              </p>
            </div>

            <div className="flex gap-3">
              <Button
                onClick={generateConsultationCard}
                disabled={isDownloading}
                className="flex-1 bg-blue-600 hover:bg-blue-700"
                data-testid="download-consultation-card"
              >
                <Download className="h-4 w-4 mr-2" />
                {isDownloading ? 'Generating...' : 'Download Card'}
              </Button>
              
              <Button
                variant="outline"
                onClick={onClose}
                className="flex-1"
                data-testid="close-modal"
              >
                <X className="h-4 w-4 mr-2" />
                Close
              </Button>
            </div>
          </div>

          <div className="text-xs text-gray-500 text-center">
            💡 The consultation card includes patient details and space for doctor notes
          </div>
        </div>
      </DialogContent>
    </Dialog>
  );
}